services:
  # Servicio de la aplicación Python (loader)
  tfm_ai_data_loader:
    build:
      context: ./python_custom
    container_name: tfm_ai_data_loader_container
    volumes:
      - .:/app              # Código de la app
      - ./files:/files            # Nuevo: todo el directorio "file" montado dentro del contenedor
    working_dir: /app
    command: >
      /venv/bin/python ./app/main_tfm.py && tail -f /dev/null  # Ejecutar el script y luego mantener el contenedor activo
    networks:
      - cia-infrastructure_tfm_ai_network  # Red compartida con `cia-infrastructure`

# Declaración de redes externas
networks:
  cia-infrastructure_tfm_ai_network:
    external: true  # Usar la misma red externa que `cia-infrastructure`
